# Generated by Django 5.1.2 on 2025-07-24 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edtech_tracker', '0002_alter_assignment_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='desc',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('assignment', 'student')},
        ),
    ]
